pipeline {
    agent any

    stages {

        stage('build') {
            steps {
              sh '''
                 cd ./MicroServices/customer-service
                 ./mvnw -DskipTests clean compile
              '''
            }
        }

        stage('test') {
            steps {
              sh '''
                 cd MicroServices/customer-service
                     ./mvnw test
              '''
            }
        }

        stage('deliver') {
            steps {
              sh '''
                 cd MicroServices/customer-service
                     ./mvnw -DskipTests install
              '''
            }
        }

    }
}
